services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: paysplit
      POSTGRES_PASSWORD: paysplit
      POSTGRES_DB: paysplit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paysplit -d paysplit"]
      interval: 3s
      timeout: 3s
      retries: 30
  redis:
    image: redis:7
    ports:
      - "6379:6379"
